cars = ["Ford", "Chrysler", "Dodge", "Ram", "Jeep", "Chevy", "GMC"]
print(cars)
print(len(cars))
cars.append("Buick")
print(cars)
print(cars[3])
cars.insert(2, "Toyota")
print(cars)
cars.pop(4)
print(cars)
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
carsLenth = len(cars)
print("My array is", carsLenth, "elements long.")